apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: hello
          image: bash
          command: ["echo",  "Hello world"]
      restartPolicy: OnFailure
