apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesJson6902:
- target:
    group: batch
    version: v1
    kind: Job
    name: test
  path: ./job_patch_to_cron.yaml
